clc; clear; close all;
Kinematic;
%做出初始示意图的帧
frame1 = plot_screws_and_links(S1, false);
frame2 = plot_screws_and_links(S2, false);
frame3 = plot_screws_and_links(S3, false);

S_leg(1).ri = S1(1).ri;
S_leg(2).ri = S2(1).ri;
S_leg(3).ri = S3(1).ri;

frame = plot_p_r_links(p, S_leg, false);



%计算初始时的POE
%对于链1
 T_branch_1=trans_exp_screw(S1(5).xi,0)*...
 trans_exp_screw(S1(4).xi,0)*...
 trans_exp_screw(S1(3).xi,0)*...
 trans_exp_screw(S1(2).xi,0)*...
 trans_exp_screw(S1(1).xi,0)*T_01;
 %对于链2
  T_branch_2=trans_exp_screw(S2(5).xi,0)*...
 trans_exp_screw(S2(4).xi,0)*...
 trans_exp_screw(S2(3).xi,0)*...
 trans_exp_screw(S2(2).xi,0)*...
 trans_exp_screw(S2(1).xi,0)*T_01;
  %对于链3
    T_branch_3=trans_exp_screw(S3(5).xi,0)*...
 trans_exp_screw(S3(4).xi,0)*...
 trans_exp_screw(S3(3).xi,0)*...
 trans_exp_screw(S3(2).xi,0)*...
 trans_exp_screw(S3(1).xi,0)*T_01;